### ISSUE TITLE
VBAN_Send aborts after a while.

### ISSUE THREAD

**Issue by timboxyz** [TheStaticTurtle/pyVBAN#5]
VBAN_Send runs for a while then quits with the following message:-
`src/hostapi/alsa/pa_linux_alsa.c:3641: PaAlsaStreamComponent_BeginPolling: Assertion 'ret == self->nfds' failed`

I have tried different sample rates but no change and the time before aborting varies.
Looking at htop  the system (Intel© Core™ i3-3110M CPU @ 2.40GHz × 2 Linux Mint 20.1 Cinnamon) is not stressed, process taking about 5% CPU and total CPU load ~30%.

VBAN_Recv runs without stopping.

**Comment by TheStaticTurtle** [comment]
Is there an issue with VBAN_Recv then?
The issue for VBAN_Send (at least) is a pyaudio issue and seems related to your portaudio  installation (which pyaudio relies on), it looks like this is a recurrent problem (see this links):

https://stackoverflow.com/questions/59006083/how-to-install-portaudio-on-pi-properly
https://github.com/shivasiddharth/GassistPi/issues/1014

If it's the only issue I will be closing this because it way out of scope of this little vban module

**Comment by timboxyz** [comment]
VBAN_Recv works fine, thanks.
According to the link you sent, and links from that, the patch should already be in Ubuntu Groovy on which the Mint I am running is based (not on a Pi), I will dig deeper into checking version numbers to confirm, but if so it would appear the patch is not a complete fix.

Thanks for pointing me in the rightist direction to investigate though.

**Comment by timboxyz** [comment]
OK its the subtle difference between `19.6.0-1build1` and `19.6.0-1.1`. So not your problem, but thanks for the help.

**Comment by TheStaticTurtle** [comment]
Nice that you figured it out, I'm closing this issue as it's resolved

**Comment by timboxyz** [comment]
Just for info I installed `19.6.0-1.1` from the Groovy repo and the problem disappeared. However, I can now get a different issue from PyAudio (0.2.11):-

```
File "/home/tim/bin/VBAN.py", line 126, in runonce
    self.rawPcm = self.stream.read(self.chunkSize)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed
```
Reducing the samplerate seems to solve this but it would be nice if it was handled properly.
